name       : libcpuid
version    : 0.6.2
release    : 8
source     :
    - https://github.com/anrieff/libcpuid/releases/download/v0.6.2/libcpuid-0.6.2.tar.gz : 1d1cc5baab3a9efd62428d4af4d5c3f0cc6b01b617f9d661708fe1ea59e6aa81
license    : BSD-2-Clause
component  : programming.library
summary    : A small C library for x86 CPU detection and feature extraction
description: |
    libcpuid provides CPU identification for the x86 (and x86_64).
setup      : |
    %reconfigure --disable-static
build      : |
    %make
install    : |
    %make_install
check      : |
    %make test
