name       : libcpuid
version    : 0.5.0
release    : 4
source     :
    - https://github.com/anrieff/libcpuid/releases/download/v0.5.0/libcpuid-0.5.0.tar.gz : a8cee1f9078c1b205d3a1d7f9d4d0c729d2ad96c8ac2f237244003b77a2f1ad8
license    : BSD-2-Clause
component  : programming.library
summary    : A small C library for x86 CPU detection and feature extraction
description: |
    libcpuid provides CPU identification for the x86 (and x86_64).
setup      : |
    %reconfigure --disable-static
build      : |
    %make
install    : |
    %make_install
check      : |
    %make test
