name       : libcpuid
version    : 0.4.1
release    : 3
source     :
    - https://github.com/anrieff/libcpuid/archive/v0.4.1.tar.gz : 263b370d154d55e3b7246e069600b045d27c512456f051e9ce3d999318b58b61
license    : BSD-2-Clause
component  : programming.library
summary    : A small C library for x86 CPU detection and feature extraction
description: |
    libcpuid provides CPU identification for the x86 (and x86_64).
setup      : |
    %reconfigure --disable-static
build      : |
    %make
install    : |
    %make_install
check      : |
    %make test
