name       : libcpuid
version    : 0.6.1
release    : 7
source     :
    - https://github.com/anrieff/libcpuid/releases/download/v0.6.1/libcpuid-0.6.1.tar.gz : e11fdd852398499c2cfdee9c06d18d894918f7a38036a35f95b8e10b243082cd
license    : BSD-2-Clause
component  : programming.library
summary    : A small C library for x86 CPU detection and feature extraction
description: |
    libcpuid provides CPU identification for the x86 (and x86_64).
setup      : |
    %reconfigure --disable-static
build      : |
    %make
install    : |
    %make_install
check      : |
    %make test
