name       : libcpuid
version    : 0.5.1
release    : 5
source     :
    - https://github.com/anrieff/libcpuid/releases/download/v0.5.1/libcpuid-0.5.1.tar.gz : d9f1ba17eac4364e49c07ec880242904efa4b51d703399273585052e266e7ada
license    : BSD-2-Clause
component  : programming.library
summary    : A small C library for x86 CPU detection and feature extraction
description: |
    libcpuid provides CPU identification for the x86 (and x86_64).
setup      : |
    %reconfigure --disable-static
build      : |
    %make
install    : |
    %make_install
check      : |
    %make test
