name       : libcpuid
version    : '0.4.0'
release    : 2
source     :
    - git|https://github.com/anrieff/libcpuid.git : 84423b63b9ed9031e2c5512a52f21210d4af740c
license    : BSD-2-Clause
component  : programming.library
summary    : A small C library for x86 CPU detection and feature extraction
description: |
    libcpuid provides CPU identification for the x86 (and x86_64).
setup      : |
    %reconfigure --disable-static
build      : |
    %make
install    : |
    %make_install
check      : |
    %make test